# Attention si pour chaque client modifier :
#     nom des volumes : modifier "nom_entreprise"
#     port d'utilisation web : modifier "port_host"
version: '3'

services:
   db:
     image: mariadb:10.5.9
     volumes:
       - wordpress_nom_entreprise_mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:5.7.0
     ports:
       - port_host:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

volumes:
    nom_entreprise_wordpress_mysql:
